### ISSUE TITLE
NullPointerException on PubnativeRequest.setAdvertisingID

### ISSUE THREAD

**Issue by andreaboi83** [pubnative/pubnative-android-library#2]
Hello @cerberillo !!! I found on Crashlitics that the `setAdvertisingID` on the `PubnativeRequest` class sometimes throws a `NullPointerException`. I think that sometimes the `AdvertisingIdClient.AdInfo adInfo` instance can be `null` (we have a similar issue on our application).

This is the stacktrace:

```
Fatal Exception: java.lang.NullPointerException
       at net.pubnative.library.utils.Crypto.md5(Crypto.java:77)
       at net.pubnative.library.request.PubnativeRequest.setAdvertisingID(PubnativeRequest.java:331)
       at net.pubnative.library.request.PubnativeRequest$1.onAdvertisingIdClientFinish(PubnativeRequest.java:224)
       at net.pubnative.AdvertisingIdClient$2.run(AdvertisingIdClient.java:252)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5291)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

PS: we are using the 1.2.10 of the pubnative-android-mediation-sdk.

**Comment by cerberillo** [comment]
hey @andreaboi83 thank you very much for reporting again, I'm quite sure this has been handled in our beta channel, but let me check this and fix in in the public one too

**Comment by cerberillo** [comment]
@andreaboi83 can you please give some details about the impact (number of crashes, percent of crashes that this represents in your app)?? It would also be nice to know the devices where this is crashing, etc.

Meanwhile we'll work on a fi which hopefully will be released next week Monday

**Comment by andreaboi83** [comment]
http://crashes.to/s/d674be1a221

**Comment by cerberillo** [comment]
Hey @andreaboi83 again, thanks for reporting this issue, this has been fixed and delivered in the library, since the impact of this problem only affects the library I basically applied the patch from the new version `v2.3.12` and bumped the used library in the mediation to this one.

Please update when you can to avoid this issue happening again. Thanks.
