### ISSUE TITLE
mListener.get() java.lang.NullPointerException

### ISSUE THREAD

**Issue by simpleforreddit** [pubnative/pubnative-android-library#3]
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
at net.pubnative.library.tracking.PubnativeVisibilityTracker$1.onPreDraw(PubnativeVisibilityTracker.java:51)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
at android.view.Choreographer.doCallbacks(Choreographer.java:686)
at android.view.Choreographer.doFrame(Choreographer.java:621)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6126)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by RagnarR** [comment]
Hi @simpleforreddit . Thanks for your stacktrace, but could you please provide more information for it? Which version you use and how frequently this issue appear? Thanks again.

**Comment by simpleforreddit** [comment]
Hi, I'm using another mediation provider which uses your network SDK, so it could be them, but it has only happened since they updated to your latest SDK. The problem does not happen in 2.3.7.

The actual crash happens when using a RecyclerView with an adapter to load native ads. On scrolling the RecyclerView, the app will crash when it tries to show a native ad from PubNative.

**Comment by RagnarR** [comment]
@simpleforreddit ok, thanks for your information.

**Comment by RagnarR** [comment]
I applied the new fix in version 2.3.14 for this issue.
