### ISSUE TITLE
Tracking over not initialised view

### ISSUE THREAD

**Issue by cerberillo** [pubnative/pubnative-android-library#70]
If the user starts tracking over a not initialized view, we're getting the following error

```
W: threadid=83: thread exiting with uncaught exception (group=0x41a23c98)
W: threadid=83: uncaught exception occurred
W: java.lang.IllegalStateException: This ViewTreeObserver is not alive, call getViewTreeObserver() again
W:     at android.view.ViewTreeObserver.checkIsAlive(ViewTreeObserver.java:720)
W:     at android.view.ViewTreeObserver.removeOnGlobalLayoutListener(ViewTreeObserver.java:529)
W:     at android.view.ViewTreeObserver.removeGlobalOnLayoutListener(ViewTreeObserver.java:516)
W:     at net.pubnative.library.tracking.PubnativeImpressionTracker$CheckImpressionRunnable.run(PubnativeImpressionTracker.java:91)
W:     at java.lang.Thread.run(Thread.java:841)
W: threadid=83: calling UncaughtExceptionHandler
W: java.lang.IllegalStateException: This ViewTreeObserver is not alive, call getViewTreeObserver() again
W:     at android.view.ViewTreeObserver.checkIsAlive(ViewTreeObserver.java:720)
W:     at android.view.ViewTreeObserver.removeOnGlobalLayoutListener(ViewTreeObserver.java:529)
W:     at android.view.ViewTreeObserver.removeGlobalOnLayoutListener(ViewTreeObserver.java:516)
W:     at net.pubnative.library.tracking.PubnativeImpressionTracker$CheckImpressionRunnable.run(PubnativeImpressionTracker.java:91)
W:     at java.lang.Thread.run(Thread.java:841)
```

Any type of error of this kind should be avoided.

I purpose to check if `ViewTreeObserver` is active, otherwise drop the call and warn the user.

This should also be specified in the readme file, to only call startTracking when the view is in the screen.

**Comment by cerberillo** [comment]
This should be fixed now, doing tests before closing the issue
