### ISSUE TITLE
AndroidRuntimeException

### ISSUE THREAD

**Issue by cerberillo** [pubnative/pubnative-android-library#71]
This is a problem happening when we call `startTracking` from outside an activity so we pass a non activity `Context` to the `startTracking` method

```
E: FATAL EXCEPTION: main
  android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.
      at android.app.ContextImpl.startActivity(ContextImpl.java:1171)
      at android.app.ContextImpl.startActivity(ContextImpl.java:1158)
      at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
      at net.pubnative.library.request.model.PubnativeAdModel.openURL(PubnativeAdModel.java:264)
      at net.pubnative.library.request.model.PubnativeAdModel.onURLDrillerFinish(PubnativeAdModel.java:327)
      at net.pubnative.URLDriller$4.run(URLDriller.java:172)
      at android.os.Handler.handleCallback(Handler.java:808)
      at android.os.Handler.dispatchMessage(Handler.java:103)
      at android.os.Looper.loop(Looper.java:193)
      at android.app.ActivityThread.main(ActivityThread.java:5353)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
```

**Comment by cerberillo** [comment]
Started testing before closing this issue
